name: Bitgain
favicon: null
layout_spectrum: 0.0788141512311995
typography_spectrum: 0.1407970746513456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5167178953997791
  lightness: 0.2907188499812037
  saturation: 0.6515613172668964
  rhythmicContrast: 0.5317685599438846
purpose: []
